-- Optional / legacy: 依頼 fulfillment is derived from department name, not this column.
-- Only run if you still need the denormalized field.
-- ALTER TABLE `groupware_projects`
--   ADD COLUMN `parent_request_type` VARCHAR(64) NULL DEFAULT NULL
--   COMMENT 'Loại 依頼 của parent mà child đáp ứng'
--   AFTER `parent_project_id`;
