<?php
/**
 * Public API: insert or update child project without login.
 * GET or POST: key (required, security), parent_project_id (required), name (required), customer_id, project_order_type,
 * status (default completed), start_date, end_date, tantou (CAILY), caily_nouki, guis_nouki, progress,
 * department_id (default 5), amount, description.
 * If name + customer_id + project_order_type already exists then update, else insert (project_number generated by department).
 */
header('Content-Type: application/json; charset=UTF-8');

require_once __DIR__ . '/loader.php';
$controller->requiring();

$key = isset($_REQUEST['key']) ? $_REQUEST['key'] : '';
if ($key !== 'caily@123') {
    echo json_encode(array('status' => 'error', 'message_code' => 'invalid key', 'id' => null));
    exit;
}

require_once dirname(__DIR__) . '/application/model/project.php';

$params = array(
    'parent_project_id'  => isset($_REQUEST['parent_project_id']) ? $_REQUEST['parent_project_id'] : '',
    'name'               => isset($_REQUEST['name']) ? $_REQUEST['name'] : '',
    'status'             => isset($_REQUEST['status']) ? $_REQUEST['status'] : '',
    'start_date'         => isset($_REQUEST['start_date']) ? $_REQUEST['start_date'] : '',
    'end_date'           => isset($_REQUEST['end_date']) ? $_REQUEST['end_date'] : '',
    'tantou'             => isset($_REQUEST['tantou']) ? $_REQUEST['tantou'] : 'CAILY',
    'caily_nouki'        => isset($_REQUEST['caily_nouki']) ? $_REQUEST['caily_nouki'] : '',
    'guis_nouki'         => isset($_REQUEST['guis_nouki']) ? $_REQUEST['guis_nouki'] : '',
    'progress'           => isset($_REQUEST['progress']) ? $_REQUEST['progress'] : '',
    'project_order_type' => isset($_REQUEST['project_order_type']) ? $_REQUEST['project_order_type'] : '',
    'department_id'      => isset($_REQUEST['department_id']) ? $_REQUEST['department_id'] : '',
    'customer_id'        => isset($_REQUEST['customer_id']) ? $_REQUEST['customer_id'] : '',
    'amount'             => isset($_REQUEST['amount']) ? $_REQUEST['amount'] : '',
    'description'        => isset($_REQUEST['description']) ? $_REQUEST['description'] : '',
    'key'                => isset($_REQUEST['key']) ? $_REQUEST['key'] : '',
);

if($params['key'] != 'caily@123'){
    $hash['status'] = 'error';
    $hash['message_code'] = 'invalid key';
    echo json_encode($hash);
    exit;
}

$project = new Project();
$project->connect();
$hash = $project->upsert_project_public($params);
$project->close();

echo json_encode($hash);
